<h1>Users</h1>

<form action="/users" method="get">
	<input type="search" required name="term" value="<?= htmlspecialchars($term) ?>">
	<input type="submit" value="Search!">
</form>
<div><?= $flash['succes'][0] ?></div>
<?php foreach ($users as $user): ?>
    <table>
	    <tr>
		    <td>
			    <?= $user->name ?>
			</td>
			<td>
			    <?= $user->email ?>
			</td>
		</tr>
	</table>
<?php endforeach ?>
