<form action="/users" method="post">
	<div>
		<label>Name
			<input type="text"  name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
		</label>
		<?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
	</div>
	<div>
		<label>Email
			<input type="email"  name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
		</label>
		<?php if (isset($errors['email'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
	</div>
	<div>
		<label>Password
			<input type="password" name="user[password]" value="<?= htmlspecialchars($user['name']) ?>">
		</label>
		<?php if (isset($errors['email'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
	</div>
	<div>
		<label>Password confirmation
			<input type="password" name="user[passwordConfirmation]" value="<?= htmlspecialchars($user['name']) ?>">			
		</label>
		<?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
	</div>
	<div>
		<label>City
			<select name="user[city]">
				<option value="3">Moscow</option>
				<option value="1">Not Moscow</option>
			</select>
		</label>
	</div>
	<input type="submit" value="Sign Up">

</form>
